import { prisma } from '../../config/db';

export interface AIReportData {
  executiveSummary: string;
  projectSpecs: {
    name: string;
    client: string;
    area: number;
    designLevel: string;
  };
  metrics: {
    totalRooms: number;
    totalLightingPoints: number;
    totalSockets: number;
    totalDataDrops: number;
    totalLoadKw: number;
    totalBOQValue: number;
  };
  designAssumptions: string[];
  systemBreakdown: {
    lighting: string;
    power: string;
    elv: string;
  };
  risksAndWarnings: string[];
  engineerReviewDisclaimer: string;
}

export class AIReportService {
  public static async generate(projectId: string): Promise<AIReportData> {
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        rooms: true,
        boqItems: true,
        powerRequirements: true,
        elvRequirements: true,
      }
    });

    if (!project) {
      throw new Error('Project not found');
    }

    const totalRooms = project.rooms.length;
    const totalLightingPoints = project.rooms.reduce((acc, r) => acc + r.lightingPoints, 0);
    const totalSockets = project.rooms.reduce((acc, r) => acc + r.socketPoints, 0);
    const totalDataDrops = project.rooms.reduce((acc, r) => acc + r.dataPoints, 0);
    const totalLoadKw = project.powerRequirements.reduce((acc, r) => acc + (r.estimatedLoadKw || 0), 0);
    const totalBOQValue = project.boqItems.reduce((acc, r) => acc + r.total, 0);

    return {
      executiveSummary: `This preliminary design report sets out the concept calculations and quantity surveys for "${project.name}" located in ${project.city}, Qatar. The design complies with Kahramaa regulations and standard Civil Defense fire safety guidelines.`,
      projectSpecs: {
        name: project.name,
        client: project.client,
        area: project.areaSqm,
        designLevel: project.designLevel
      },
      metrics: {
        totalRooms,
        totalLightingPoints,
        totalSockets,
        totalDataDrops,
        totalLoadKw: parseFloat(totalLoadKw.toFixed(1)),
        totalBOQValue
      },
      designAssumptions: [
        'Lighting calculations utilize 60x60 recessed panels with 3200 fixture lumens.',
        'Utilization factor (UF) set to 0.6; maintenance factor (MF) set to 0.8.',
        'Structured cabling drops are dual Cat6 runs per workstation terminating on dual RJ45 sockets.',
        'BMS temperature logging is active for server racks and UPS batteries.'
      ],
      systemBreakdown: {
        lighting: `Planned ${totalLightingPoints} fixtures. Target lux levels range from 120-lux in corridors to 450-lux in workspaces.`,
        power: `Estimated peak load at ${totalLoadKw.toFixed(1)} kW. Server Room contains dedicated feeds and UPS batteries.`,
        elv: `Designed ${totalDataDrops} structural data outlets, Wi-Fi 6 coverage, CCTV cameras, and magnet locks.`
      },
      risksAndWarnings: [
        'Ceiling height schedules must be verified against actual architectural layouts.',
        'Server Room Precision A/C system sizing should be double-checked by HVAC specialists.',
        'Verify Qatar QCDD manufacturer certification lists before procurement of fire/CCTV items.'
      ],
      engineerReviewDisclaimer: 'IMPORTANT SAFETY DISCLAIMER: This document represents a preliminary concept estimation generated by the SAQR AI automation brain. All engineering calculations, designs, and BOQs must be validated, stamped, and approved by a licensed professional consultant engineer before procurement, construction, or installation.'
    };
  }
}
